name: Publish to NPM

on:
  release:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          yarn
          yarn build
        env:
          CI: true
      - name: Publish to NPM
        uses: luvies/action-yarn-publish@v0.1.1
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
